name: Build AntiTor (Windows x64)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  OUTPUT_NAME: "AntiTor"
  COMPILER_FLAGS: "-std=c++17 -static -static-libgcc -static-libstdc++ -mwindows -lshlwapi -lversion -Wl,--subsystem,windows"

jobs:
  build:
    runs-on: windows-latest
    name: "Build ${{ env.OUTPUT_NAME }}"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        uwp: false
        spectre: true

    - name: Install MinGW
      run: |
        choco install mingw -y --force --ignore-checksums
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH

    - name: Compile ${{ env.OUTPUT_NAME }}
      run: |
        g++ ${{ env.COMPILER_FLAGS }} -o ${{ env.O
